[snowflakeconnection]
  account = account_url'A6547988765371-WDB90849' 
  user = 'nswetha'  
  role = 'sr_dev_etl'  
  warehouse = 'dev_data_engineer_xs_wh'  
  database = 'GROWTH_PROTOCOL_TESTING_DB'     # optional but recommended  
  password = 'Gpswetha2'     # if not using other auth methods  
