name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Changing Permissions of config.toml file
        run: |
          chown $USER ".github/workflows/config.toml"
          chmod 0600 ".github/workflows/config.toml"

      - name: Use Python 3.12.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.12.x

      - name: Run schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f "$GITHUB_WORKSPACE/migrations" --connections-file-path .github/workflows/config.toml --connection-name snowflakeconnection  -c "TEST_DB.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table  
