name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    env:
      # Add your secrets here for clarity; these should be set in GitHub Secrets
      SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.12.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.12.x

      - name: Generate config.yml with secrets
        run: |
          cat > config.yml <<EOF
          snowflake:
            account: "${{ env.SNOWFLAKE_ACCOUNT }}"
            user: "${{ env.SNOWFLAKE_USER }}"
            password: "${{ env.SNOWFLAKE_PASSWORD }}"
            warehouse: "${{ env.SNOWFLAKE_WAREHOUSE }}"
            database: "${{ env.SNOWFLAKE_DATABASE }}"
            schema: "${{ env.SNOWFLAKE_SCHEMA }}"
          EOF

      - name: Verify generated config.yml
        run: cat config.yml

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange
        run: schemachange deploy -c config.yml
