name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - 'test_twitter_rda.py'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change permissions of config.toml
        run: |
          chown $USER ".github/workflows/config.toml"
          chmod 0600 ".github/workflows/config.toml"

      - name: Setup Python 3.12
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.12

      - name: Identify changed files
        id: changed_files
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main...HEAD)
          echo "changed_files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Check if test_twitter_rda.py was changed
        id: check_tests
        run: |
          echo "${{ steps.changed_files.outputs.changed_files }}" | grep -E 'test_twitter_rda.py' || echo "No relevant test changes"
        continue-on-error: true

      - name: Run tests if relevant files changed
        if: steps.check_tests.outputs.changed_files != ''
        run: |
          python3 -m unittest discover -p 'test_twitter_rda.py'
        id: run_tests
        continue-on-error: true

      - name: Get test result outcome
        id: test_outcome
        run: |
          if [ "${{ steps.run_tests.conclusion }}" == "success" ]; then
            echo "outcome=success" >> $GITHUB_OUTPUT
          elif [ "${{ steps.run_tests.conclusion }}" == "failure" ]; then
            echo "outcome=failure" >> $GITHUB_OUTPUT
          else
            echo "outcome=skipped" >> $GITHUB_OUTPUT
          fi

      - name: Post comment on PR about failure
        if: steps.test_outcome.outputs.outcome == 'failure' && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `⚠️ **Test Failure Detected**\n\nTests for 'test_twitter_rda.py' have failed during deployment.\n\nChanged files:\n${{ steps.changed_files.outputs.changed_files }}\n\nPlease review the test logs for details.`
            });
          
      - name: Proceed to deployment if tests succeeded
        if: steps.test_outcome.outputs.outcome == 'success'
        run: |
          echo "Tests passed. Proceeding with deployment..."
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          pip install schemachange
          schemachange -f "$GITHUB_WORKSPACE/migrations" \
            --connections-file-path .github/workflows/config.toml \
            --connection-name snowflakeconnection \
            -c "TEST_DB.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
